#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
# autospec version: v21
# autospec commit: 542402611043
#
Name     : libversion
Version  : 3.0.3
Release  : 1
URL      : https://github.com/repology/libversion/archive/3.0.3/libversion-3.0.3.tar.gz
Source0  : https://github.com/repology/libversion/archive/3.0.3/libversion-3.0.3.tar.gz
Summary  : Version comparison library
Group    : Development/Tools
License  : MIT
Requires: libversion-bin = %{version}-%{release}
Requires: libversion-lib = %{version}-%{release}
Requires: libversion-license = %{version}-%{release}
BuildRequires : buildreq-cmake
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
# libversion
<a href="https://repology.org/metapackage/libversion/versions">
<img src="https://repology.org/badge/vertical-allrepos/libversion.svg" alt="libversion packaging status" align="right">
</a>

%package bin
Summary: bin components for the libversion package.
Group: Binaries
Requires: libversion-license = %{version}-%{release}

%description bin
bin components for the libversion package.


%package dev
Summary: dev components for the libversion package.
Group: Development
Requires: libversion-lib = %{version}-%{release}
Requires: libversion-bin = %{version}-%{release}
Provides: libversion-devel = %{version}-%{release}
Requires: libversion = %{version}-%{release}

%description dev
dev components for the libversion package.


%package lib
Summary: lib components for the libversion package.
Group: Libraries
Requires: libversion-license = %{version}-%{release}

%description lib
lib components for the libversion package.


%package license
Summary: license components for the libversion package.
Group: Default

%description license
license components for the libversion package.


%prep
%setup -q -n libversion-3.0.3
cd %{_builddir}/libversion-3.0.3

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1733423464
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%cmake ..   -G 'Unix Makefiles'
make  %{?_smp_mflags}
popd

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
cd clr-build; make test

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1733423464
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libversion
cp %{_builddir}/libversion-%{version}/COPYING %{buildroot}/usr/share/package-licenses/libversion/4e61d2cfdc85f69a6016e814625a41bdd5ea72fd || :
export GOAMD64=v2
GOAMD64=v2
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/version_compare
/usr/bin/version_sort

%files dev
%defattr(-,root,root,-)
/usr/include/libversion/config.h
/usr/include/libversion/export.h
/usr/include/libversion/version.h
/usr/lib64/cmake/libversion/libversionConfig-relwithdebinfo.cmake
/usr/lib64/cmake/libversion/libversionConfig.cmake
/usr/lib64/libversion.so
/usr/lib64/pkgconfig/libversion.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libversion.so.1
/usr/lib64/libversion.so.1.0.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libversion/4e61d2cfdc85f69a6016e814625a41bdd5ea72fd
